### ISSUE TITLE
Performance test doesn't seem accurate, seems much slower than lodash.get.

### ISSUE THREAD

**Issue by dylang** [RIP21/ts-get#3]
Hi, thanks for creating this, I've been hoping a better `_.get` existed for TypeScript.

I was confused how `try/catch` could be faster than lodash's get, so I simplified the performance test and got very different results, suggesting `ts-get` is many times slower than `_.get`:

<img width="906" alt="Screen Shot 2019-04-09 at 4 23 51 PM" src="https://user-images.githubusercontent.com/51505/55832629-f40bc980-5ae3-11e9-80d1-79ce96f47d32.png">

https://jsperf.com/ts-get-vs-get/4

The problem with your original tests:
 * Only one level deep.
 * Not testing the fail case.
 * Comparing a single run to an array of runs.

It's possible I did something wrong in the tests, it took me a couple tries to get it right.

**Comment by RIP21** [comment]
@dylang thanks a lot for your input! :) 
I thought I do test fail case tho :( But I missed that it should be nested to throw an Error. Try catch is indeed way slower :( 
I'll update the test case and I'll remove false advertisement!
Thanks once again!
Funny thing that I updated this README only today :D
